### ISSUE TITLE
response null

### ISSUE THREAD

**Issue by MeGaPk** [skywite/SWNetworking#10]
Hello!

When i tried make request: GET https://hideme.ru/api/serverlist.php?out=js
But: "response as String (null)"

Code from example:
```
SWGETRequest *getRequest = [[SWGETRequest alloc]init];
    [getRequest startDataTaskWithURL:@"https://hideme.ru/api/serverlist.php?out=js" parameters:nil success:^(NSURLSessionDataTask *uploadTask, id responseObject) {
        NSLog(@"response as String %@", getRequest.responseString);

    } failure:^(NSURLSessionTask *uploadTask, NSError *error) {
    
    }];
```

**Comment by MeGaPk** [comment]
Okay. Site returned by  Windows 1251 (cp1251) encoding.

Just need get NSData and after that:
```
                NSLog(@"Response: %@", [[NSString alloc] initWithData:responseObject encoding:NSWindowsCP1251StringEncoding]);
```
But i dont see any errors in failure, just empty response string... please fix that bug :(

**Comment by isamankumara** [comment]
hi Thanks for the telling this. 
But 
we can't handle this because we can't see any error returning with 

```NSString alloc]initWithData:data encoding:NSUTF8StringEncoding]```

because null response also retuning null. But we can add give a parameter to set the encoding 

For now you can do following things to fix this. 

Create you own ResponseDataType Class

Eg : 
```
@interface WindowsCP1251StringDataType : SWResponseDataType
```

and override two method as bellow
```
-(id)responseOjbect:(NSHTTPURLResponse *) response data:(NSData *)data{
    
    self.responseCode = (int)[response statusCode];
    
    return [[NSString alloc]initWithData:data encoding:NSWindowsCP1251StringEncoding];
    
}
-(id)responseOjbectFromdData:(NSData *)data{
    
    return [[NSString alloc]initWithData:data encoding:NSWindowsCP1251StringEncoding];
}
```

Now your request should be as follows

```
SWGETRequest *getRequest = [[SWGETRequest alloc]init];
    **getRequest.responseDataType = [WindowsCP1251StringDataType type];**
    [getRequest startDataTaskWithURL:@"https://hideme.ru/api/serverlist.php?out=js" parameters:nil success:^(NSURLSessionDataTask *uploadTask, id responseObject) {
        NSLog(@"response as String %@", getRequest.responseString);

    } failure:^(NSURLSessionTask *uploadTask, NSError *error) {
    
    }];

```

Anyway will add something to show encoding error and add ability to change encoding. Thanks for the feedback.

**Comment by MeGaPk** [comment]
Hello!
Very fast answer, thanks! 👍 
So, my suggestion about that:
When we receive NSDate, we see not null data :)

After convert to string, we see zero, and after that, write error, maybe... 

About SWResponseJSONDataType - He have error, when converting failed. But NSJSONSerialization not support Windows1251....

**Comment by isamankumara** [comment]
added error and will close the ticket. please update your pod
