### ISSUE TITLE
no localizedCaseInsensitiveContainsString() in iOS 7

### ISSUE THREAD

**Issue by patBurger** [skywite/SWNetworking#2]
Hi,
there's a fault in your commit 0db70b2585d073b7799e30b58dea75f14d0155c3 you pushed a day ago. The SWNetworking.podspec states support for iOS7, but in SWRequestOperation.m you use NSString localizedCaseInsensitiveContainsString method which is not available for iOS7. 

greets!

**Comment by isamankumara** [comment]
Thanks for the information and its fixed.
